spring:
  datasource:
    url:  jdbc:mysql://db-flde3.pub-cdb.ntruss.com:3306/hot-deal
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hojin
    password: Janghojin00@
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

